### PR TITLE
Fix the FOR loop count and increment formulas

### LINKED ISSUE #1033: `FOR` loops have some unexpected edge cases
As mentioned in #1003.

```
FOR x, $8000_0000, $6000_0000, $4000_0000
  PRINTLN x
ENDR
PRINTLN "done ", x
```

This prints `$80000000` and then `done $C0000000`.

```
FOR x, $8000_0000, $7000_0000, $4400_0000
  PRINTLN x
ENDR
PRINTLN "done ", x
```

This prints `$80000000` and then `done $C4000000`.

### PR DESCRIPTION
**Pull request by Rangi42**
Fixes #1033

Remember when testing that values in rgbasm are always signed; it's just the count calculation that needs to use an unsigned |stop - start| difference.

The formula now uses 64-bit math. It's not practical to test every possible combination of (start, stop, step) values, but we can do the analogous case with 8-bit values. [This test program](https://godbolt.org/z/Wvbcv7sWb) does not find any flaws:

```c
#include <stdio.h>
#include <stdint.h>

int main() {
    long num = 0;
    for (int istart = -0x80; istart < 0x80; istart++) {
        for (int istop = -0x80; istop < 0x80; istop++) {
            for (int istep = -0x80; istep < 0x80; istep++) {
                int8_t bstart = (int8_t)istart;
                int8_t bstop = (int8_t)istop;
                int8_t bstep = (int8_t)istep;

                int icount = 0;
                if (istep > 0 && istart < istop)
                    icount = ((istop - istart) / istep + 1) & 0xff;
                else if (istep < 0 && istop < istart)
                    icount = ((istart - istop) / -istep + 1) & 0xff;

                uint8_t bcount = 0;
                if (bstep > 0 && bstart < bstop)
                    bcount = (uint8_t)((uint16_t)((int16_t)bstop - bstart) / bstep) + 1;
                else if (bstep < 0 && bstop < bstart)
                    bcount = (uint8_t)((uint16_t)((int16_t)bstart - bstop) / -bstep) + 1;

                if ((int)bcount != icount)
                    printf("start=%d, stop=%d, step=%d => count=%d NOT %d!\n",
                        istart, istop, istep, icount, (int)bcount);

                num++;
            }
        }
    }
    printf("all %ld cases done\n", num);
    return 0;
}
```

@aaaaaa123456789 Please try breaking this further?

### CODE REVIEW

File: src/asm/fstack.c [hunk 1]
```diff
@@ -240,7 +240,9 @@ bool yywrap(void)
 
 		// If this is a FOR, update the symbol value
 		if (contextStack->forName && fileInfo->iters[0] <= contextStack->nbReptIters) {
-			contextStack->forValue += contextStack->forStep;
+			// Avoid arithmetic overflow runtime error
```
Comment (Rangi42) [inline src/asm/fstack.c:243]: rpn.c already does addition of user-defined variables as unsigned, for exactly this reason. We just had missed that case in `FOR` loops so far.

File: src/asm/fstack.c [hunk 2]
```diff
@@ -511,9 +513,9 @@ void fstk_RunFor(char const *symName, int32_t start, int32_t stop, int32_t step,
 	uint32_t count = 0;
 
 	if (step > 0 && start < stop)
-		count = (stop - start - 1) / step + 1;
+		count =  (uint32_t)((uint64_t)((int64_t)stop - start - 1) / step) + 1;
```
Comment (Rangi42) [inline src/asm/fstack.c:516]: I suspect this could be done with at least one fewer cast, but this is explicit about what it's doing, and it works as-is.

File: src/asm/fstack.c [hunk 3]
```diff
@@ -511,9 +513,9 @@ void fstk_RunFor(char const *symName, int32_t start, int32_t stop, int32_t step,
...
 	else if (step < 0 && stop < start)
-		count = (start - stop - 1) / -step + 1;
+		count = (uint32_t)((uint64_t)((int64_t)start - stop - 1) / -step) + 1;
```
Comment (aaaaaa123456789) [inline src/asm/fstack.c:518]: If you're going to be careful about UB, remember that `-step` is UB if `step` is `INT32_MIN` (assuming `int32_t` is at least as wide as `int`, which in practice it will almost always be). You should cast `step` to `int64_t` _before_ negating it.

**Review by aaaaaa123456789 — CHANGES_REQUESTED** [review]
Just a few minor things. By the way, I'd add more tests with a step value of `$80000000`, since that's one of the hardest to get right due to the weird semantics of the lowest possible value.

File: src/asm/fstack.c (hunk 1 above)
Comment (Rangi42) [reply src/asm/fstack.c:243]: Thanks, I've added an explicit `int32_t` cast.

**Comment by Rangi42** [comment]
Thank you @aaaaaa123456789 ! I've accounted for your comments, and added more tests, plus more detailed output.

File: src/asm/fstack.c (hunk 1 above)
Comment (aaaaaa123456789) [reply src/asm/fstack.c:243]: Adding a cast doesn't fix the situation: it's the conversion that is UB, not the fact that it is implicit. (C doesn't make a difference between implicit and explicit conversions.)

**Comment by aaaaaa123456789** [comment]
The cast doesn't quite do what you want; the rest is good!

**Comment by Rangi42** [comment]
Fixed after discussion in Discord. :)

**Review by aaaaaa123456789 — APPROVED** [review]
LGTM

**Comment by Rangi42** [comment]
`error: operand of ?: changes signedness from ‘int’ to ‘uint32_t’ {aka ‘unsigned int’} due to unsignedness of other operand [-Werror=sign-compare]` 😭 still more nitpicking to do

**Comment by aaaaaa123456789** [comment]
> `error: operand of ?: changes signedness from ‘int’ to ‘uint32_t’ {aka ‘unsigned int’} due to unsignedness of other operand [-Werror=sign-compare]` 😭 still more nitpicking to do

Oh, that's just because of the `0`. Make it `0u` and it will stop crying. (This is why this warning is pointless — the code works either way.)

**Comment by Rangi42** [comment]
Fixed and rebased. :)

File: src/asm/fstack.cpp [hunk 4]
```diff
@@ -240,7 +240,11 @@ bool yywrap(void)
 
 		// If this is a FOR, update the symbol value
 		if (contextStack->forName && fileInfo->iters[0] <= contextStack->nbReptIters) {
-			contextStack->forValue += contextStack->forStep;
+			// Avoid arithmetic overflow runtime error
```
Comment (ISSOtm) [inline src/asm/fstack.cpp:243]: I want to ~~die~~ stop using these wretched languages, but ok

**Review by ISSOtm — APPROVED** [review]

File: src/asm/fstack.cpp (hunk 4 above)
Comment (Rangi42) [reply src/asm/fstack.cpp:243]: Does C++20 have a better alternative?
