### PR TITLE
Prevent defining invalid local labels

### LINKED ISSUE #913: [Bug] Multiple dots in identifiers behave inconsistently
This is currently a legal program:

```
SECTION "test", ROM0[0]
Main:
	db 0
.local1:
	db 1
Main.local2:
	db 2
Main....local3:
	db 3
....local4
	db 4
Main.:
	db 5
```

```
$ rgbasm -Weverything -o foo.o foo.asm
$ rgblink -o foo.gb -n foo.sym foo.o
$ cat foo.sym
; File generated by rgblink
00:0000 Main
00:0001 Main.local1
00:0002 Main.local2
00:0003 Main....local3
00:0004 Main....local4
00:0005 Main.
```

However, the odd label cannot be referenced. `dw Main....local3` fails to assemble with "`FATAL: 'Main....local3' is a nonsensical reference to a nested local symbol`". `dw .local3` assembles but fails to link with "`error: Unknown symbol "Main.local3"`".

Furthermore, this assembles:

```
Main:
	db 0
.local1:
	db 1
Main.local2:
	db 2
Main.abc.local3:
	db 3
```
```
00:0003 Main.abc.local3
```

But "`Main.abcd.local3`" fails with "`'Main.abcd.local3' is a nonsensical reference to a nested local label`".

Short-term, I think any identifier with more than one `.` in it, or with a trailing `.`, or with a starting `.` and no parent scoped label, should be rejected. So `Main....local3`, `....local4`, and `Main.abc.local3` would all fail as "nonsensical reference"s right away.

Long-term, it might be useful to allow nested scopes, but I doubt it. For one thing, there's no simple way to go up a scope except by starting a new non-local label in the main scope.

### PR DESCRIPTION
**Pull request by Rangi42**
Fixes #913

### CODE REVIEW

File: src/asm/symbol.c [hunk 1]
```diff
@@ -533,42 +533,51 @@ static struct Symbol *addLabel(char const *symName)
...
 		error("Local label '%s' in main scope\n", symName);
 		return NULL;
 	}
+	assert(!strchr(labelScope, '.')); /* Assuming no dots in `labelScope` */
+
+	char fullName[MAXSYMLEN + 1];
+	char const *localName = strchr(symName, '.');
+
+	assert(localName); /* There should be at least one dot in `symName` */
+	assert(localName[0] == '.'); /* `localName` should start with a dot */
```
Comment (ISSOtm) [inline src/asm/symbol.c:550]: This is guaranteed by the interface of `strchr` as long as `localName` is non-NULL, so this can be removed.

File: src/asm/symbol.c [hunk 2]
```diff
@@ -533,42 +533,51 @@ static struct Symbol *addLabel(char const *symName)
...
+			   symName);
+	}
+	/* Check for more than one dot in `localName` */
+	if (strchr(localName + 1, '.'))
+		fatalerror("'%s' is a nonsensical reference to a nested local label\n",
+			   symName);
 
-	char fullname[MAXSYMLEN + 1];
+	if (localName == symName) {
+		assert(symName[0] == '.');
```
Comment (ISSOtm) [inline src/asm/symbol.c:562]: Due to the pointer equality, we already checked for this above.

**Review by ISSOtm — CHANGES_REQUESTED** [review]

**Review by ISSOtm — APPROVED** [review]
There is one style guide mistake, but at this point I'm kinda over nitpicking that until #612 is done. Which we really need to do, by the way.
