### PR TITLE
Consistent behavior with missing or incorrect arguments

### LINKED ISSUE #1131: show help if rgbgfx is invoked without params
invoking rgbgfx without any parameters, or with incorrect parameters does not show help, unlike rgbasm or rgblink

### LINKED ISSUE #1132: rgbfix appears to "hang" if no rom file is specified
i am not sure how to describe this one,
also happened for `rgbgfx -` iirc,
and isso asked me to mention that it should "warn if stdin is a TTY in the text",
hopefully someone better describes this one

### PR DESCRIPTION
**Pull request by Rangi42**
Fixes #1131
Fixes #1132

- Running `rgbasm`, `rgblink`, `rgbgfx`, or `rgbfix` with an incorrect argument (e.g. `--foobar`) will give an "unrecognized option" error, show the usage information, and exit.
- Running `rgbasm`, `rgblink`, `rgbgfx`, or `rgbfix` without any arguments will give a fatal error, show the usage information, and exit.

Previously, running `rgbfix` without any arguments would default to processing `-` (stdin). Now you need to explicitly pass `-`.

### CODE REVIEW

**Comment by ISSOtm** [comment]
What good is `rgbfix` useful for without any arguments?

It may be worth aligning its behaviour with the other three, and mentioning "use `rgbfix -` if you want to simply pipe the input" or something.

**Comment by Rangi42** [comment]
> What good is `rgbfix` useful for without any arguments?
> 
> It may be worth aligning its behaviour with the other three, and mentioning "use `rgbfix -` if you want to simply pipe the input" or something.

I didn't want to accidentally break someone's workflow who's using `rgbasm -o - foo.asm | rgblink -o - - | rgbfix` instead of `| rgbfix -`. But yeah, if it's okay to break that negligible possibility, I'd rather have them be consistent.

**Comment by ISSOtm** [comment]
Well, it's unlikely enough, we've had several reports of people being confused by RGBFIX's behaviour (appearing to hang), and we're not WG14, so I think it's worth breaking.

We'll have to add a note in the changelog to highlight the breakage as intentional for future reference, I guess.

**Comment by pinobatch** [comment]
A couple years ago, I wrote a compression tool in C to avoid a Python dependency in a replacement boot ROM. I checked whether `isatty(stdout)` before trying to compress to standard output and [whether `isatty(stdin)`](https://github.com/pinobatch/little-things-gb/blob/680f8ad85a74e903c3899c1e779b3eae76c051cb/common/tools/pb8.c#L347-L351) before trying to decompress from standard input. The user would get an error like this:

    pb8: cannot compress to terminal; try redirecting stdout or pb8 --help

I had to do a bit of `#ifdef` at the top to make it work on both POSIX and Windows systems.

**Comment by aaaaaa123456789** [comment]
Just break this; the fix is easy. But please do mention it, so people know how to fix this.

**Comment by Rangi42** [comment]
Done: `rgbfix` is now consistent with the rest, and man pages explicitly mention `-`.

**Comment by Rangi42** [comment]
> > I didn't want to accidentally break someone's workflow ...


> Well, it's unlikely enough, we've had several reports of people being confused by RGBFIX's behaviour (appearing to hang), and we're not WG14, so I think it's worth breaking.


> Just break this; the fix is easy. But please do mention it, so people know how to fix this.


Of course, the `rgbfix` tests themselves depended on this, and now they're all breaking. :P

**Review by ISSOtm — COMMENTED** [review]
What's the rationale for making all of the "print usage" functions "noreturn"? It feels like it's obscuring the control flow IMO.

**Comment by Rangi42** [comment]
> What's the rationale for making all of the "print usage" functions "noreturn"? It feels like it's obscuring the control flow IMO.

Some of them already called `exit()` inside, and the ones that didn't were always immediately followed by `exit()` anyway.

**Comment by aaaaaa123456789** [comment]
I'd say this is pretty standard, because if you're printing usage information, you're not doing anything else. I've never seen a program print usage information and _not_ exit right after.
Exiting from inside those functions is quite common, too.

**Comment by ISSOtm** [comment]
It would make sense to print an extra line afterwards, for example. I'd rather have the flow control be explicit in the caller.

**Comment by Rangi42** [comment]
> It would make sense to print an extra line afterwards, for example. I'd rather have the flow control be explicit in the caller.

Okay.

File: src/fix/main.c [hunk 1]
```diff
@@ -1401,7 +1401,6 @@ do { \
 			break;
 
 		default:
-			fprintf(stderr, "FATAL: unknown option '%c'\n", ch);
```
Comment (ISSOtm) [inline src/fix/main.c:1404]: I don't think it's good UX to print out the usage without saying why we're doing so

**Review by ISSOtm — CHANGES_REQUESTED** [review]
Great! The UX should improve that much overall. Thank you!

File: src/fix/main.c (hunk 1 above)
Comment (Rangi42) [reply src/fix/main.c]: Okay, I've added this to all the programs.

**Review by ISSOtm — APPROVED** [review]
