### PR TITLE
Fix `SECTION UNION` alignment depending on piece order

### LINKED ISSUE #1881: Inconsistency with section placement involving alignment
### Background

This behavior was noticed in https://github.com/ariscop/polishedcrystal/tree/audio. In [`ram/wram0.asm`](https://github.com/ariscop/polishedcrystal/blob/audio/ram/wram0.asm#L1111), it has:
```asm
	assert @ & $FF == 0, "wMPNotes must be 8-bit aligned"
```
I thought this could be simplified to `align 8` for the same effect. But in fact replacing the `assert` with an `align` fails:
```
error: The linker script assigns section "Misc 1326" to address $c650, but that would be ALIGN[8, 80] instead of the requested ALIGN[8, 0]
```
It apparently has something to do with how [`engine/pc/bills_pc_ui.asm`](https://github.com/ariscop/polishedcrystal/blob/audio/engine/pc/bills_pc_ui.asm#L3643) has a `LOAD UNION "Misc 1326", WRAM0` which gets linked first.

I have tried to reduce this to an MVP test case below.

### `a.asm`

```asm
SECTION "R1", WRAM0
        ds $77

SECTION "R2", WRAM0
        ds $ef

SECTION UNION "U", WRAM0
        ds $52e

SECTION UNION "U", WRAM0
wStart::
        ds $89
        assert @ & $FF == 0, "wContent must be 8-bit aligned"
        align 8
wContent::
        ds $111
wEnd::
```

### `b.asm`

```asm
SECTION "ROM", ROM0
LOAD UNION "U", WRAM0
        ds 1
ENDL
```

### `a.link`

```
WRAM0
        align 8
        "R1"
        "U"
        "R2"
```

### Without linker script

```console
$ rgbasm -o a.o a.asm
$ rgbasm -o b.o b.asm
$ rgblink -m - a.o b.o
SUMMARY:
        ROM0: 1 byte used / 16383 free
        WRAM0: 1684 bytes used / 2412 free

ROM0 bank #0:
        SECTION: $0000-$0000 ($0001 byte) ["ROM"]
        EMPTY: $0001-$3fff ($3fff bytes)
        TOTAL EMPTY: $3fff bytes

WRAM0 bank #0:
        SECTION: $c000-$c076 ($0077 bytes) ["R1"]
        SECTION: $c077-$c5a4 ($052e bytes) ["U"]
                 $c077 = wStart
                 $c100 = wContent
                 $c211 = wEnd
        SECTION: $c5a5-$c693 ($00ef bytes) ["R2"]
        EMPTY: $c694-$cfff ($096c bytes)
        TOTAL EMPTY: $096c bytes
$ rgblink -m - b.o a.o
error: wContent must be 8-bit aligned
    at a.asm(13)
Linking failed with 1 error
```

### With linker script

```console
$ rgblink -m - a.o b.o -l a.link
SUMMARY:
        ROM0: 1 byte used / 16383 free
        WRAM0: 1684 bytes used / 2412 free

ROM0 bank #0:
        SECTION: $0000-$0000 ($0001 byte) ["ROM"]
        EMPTY: $0001-$3fff ($3fff bytes)
        TOTAL EMPTY: $3fff bytes

WRAM0 bank #0:
        SECTION: $c000-$c076 ($0077 bytes) ["R1"]
        SECTION: $c077-$c5a4 ($052e bytes) ["U"]
                 $c077 = wStart
                 $c100 = wContent
                 $c211 = wEnd
        SECTION: $c5a5-$c693 ($00ef bytes) ["R2"]
        EMPTY: $c694-$cfff ($096c bytes)
        TOTAL EMPTY: $096c bytes
$ rgblink -m - b.o a.o -l a.link
error: The linker script assigns section "U" to address $c077, but that would be ALIGN[8, 119] instead of the requested ALIGN[8, 0]
    at a.link(4)
Linking failed with 1 error
```

### PR DESCRIPTION
**Pull request by Rangi42**
Fixes #1881

The one-line fix was found by @vulcandth using OpenAI Codex (in 5 minutes!), prompted with the issue description I had written. Its conclusion:

> Root cause was in how rgblink merges `SECTION UNION` pieces: when a later object contributed a stronger alignment, the linker updated the alignment mask but accidentally kept the old alignment offset (often 0). That made the combined section’s required `ALIGN[power, offset]` depend on which object file was seen first.  
> Patched the merge logic to copy `alignOfs` alongside `alignMask` when adopting a stronger alignment constraint.

I'm pretty confident this is a correct fix, given that it now makes `checkSectUnionCompat` clearly symmetrical with `checkFragmentCompat`. I can add more test cases if we think of any that would cover appropriate new scenarios.

Also confirmed that it builds https://github.com/ariscop/polishedcrystal/tree/audio even with an `align 8` now.

### CODE REVIEW

File: src/link/section.cpp [hunk 1]
```diff
@@ -25,91 +25,71 @@ void sect_ForEach(void (*callback)(Section &)) {
...
-static void checkFragmentCompat(Section &target, Section &other) {
-	if (other.isAddressFixed) {
-		uint16_t org = other.org - target.size;
-		checkAgainstFixedAddress(target, other, org);
-		target.isAddressFixed = true;
-		target.org = org;
-	} else if (other.isAlignFixed) {
-		uint32_t ofs = (other.alignOfs - target.size) & other.alignMask;
-		if (checkAgainstFixedAlign(target, other, ofs)) {
+		} else if (!target.isAlignFixed || (other.alignMask > target.alignMask)) {
```
Comment (ISSOtm) [inline src/link/section.cpp]: To avoid repeating the `isAlignFixed` condition, I think I would prefer `else if (target.isAlignFixed)` above, and a nested `if (other.alignMask ...)` inside of that.

(Also, score one for pattern-matching, I guess!)

**Comment by ISSOtm** [comment]
I'm personally not convinced by the use of a LLM here, since the hard work (of narrowing the bug down) had already been performed, and a human would've been able to perform the fix in the same five minutes.

*[EDIT: Some friends asked me about this, and I've given a more lengthy analysis of my stance, but wish to reproduce it in a more public place for easier future linking to.]*

The intelligence and expertise sought out of us developers lies as much in the [“I know what I need, so I'm going to do this”](https://www.reddit.com/r/developpeurs/comments/1q5qla5/mon_exp%C3%A9rience_avec_la_transformation_du_m%C3%A9tier/) as it does in evaluating whether “this” is adapted or not; delegating the actual code modifications to a third party (be it a LLM or an intern, that changes nothing for you) implies detaching yourself from them, and thus stop evolving your understanding of the code—thus losing your expertise through aging, like a manager.

For context to the above PR and linked issue, Rangi raised the original bug in polishedcrystal to me yesterday, asking for help narrowing it down; I replied “I think the error is in this component[^component], here's a sequence of actions we can take to verify that (and thus pare down how much code may be involved and where), huh they are consistent, thus the error must be in another component, :yawning_face: well let's investigate the rest tomorrow”.

Had we delegated writing the code entirely to a LLM, the codebase would be a black box to us, and thus I would've been unable to provide the above reasoning. At best, I could've thrown the black box at another one, asking a LLM to analyse the codebase and hope that its analysis made sense.

Unless one trains a LLM on a specific codebase, it's never going to gain specific domain knowledge, and thus is far more likely to answer incorrectly[^junior], *and* you'd be none the wiser.

Where it all gets to a head is partial bug fixes: for example, if the LLM had judged that a `if (section->alignOfs == 0) section->alignOfs = 87;` would be the appropriate fix to the above issue (e.g. in the section-reading code, or in the piece-merging functions, or whatever), then yes that would let polishedcrystal build and would turn the test case green[^test_author], but I hope we all agree it wouldn't actually fix the bug.

And, yes, the exact one-liner above is clearly wrong to at least this project's two maintainers; but, increase the complexity of the putative submitted patch a little, or decrease your knowledge of the codebase (such as by the “black-boxing” process I outlined in an earlier paragraph), and judging whether a solution is “truly” appropriate becomes much, much more tricky.

**tl;dr**: A LLM does not learn from repeated interactions, while delegating the actual work of typing the words and laying out the logic ourselves creates distance from the code (more as a result of losing subconscious / “muscle-memory” engagement) that weakens our very ability to oversee and evaluate the LLM's output. I would parallel this to what I've heard about “learning to type before to hand-write reduces your understanding of language”, and also the more general sentiment that LLM usage amounts to [“rolling up the ladder behind us”](https://xeiaso.net/blog/2025/rolling-ladder-behind-us/).

[^component]: RGBASM to be precise, but that's irrelevant to the point being made here.
[^junior]: “like a junior”, I would add with a little wince, since juniors *are* essential because seniors age and move on; what makes a good junior, in my eyes, *is* entirely their ability to learn and thus turn into a senior. If my understanding of LLMs is correct, they aren't continuously trained, thus being *permanent* juniors, thereby having all of the downsides and none of the upsides.
[^test_author]: Assuming that the test case is correct in the first place, but the process of writing it is practically equivalent to narrowing the bug down, and the wrong test case will likely lead to the wrong bug fix, so IMO this entire discussion recursively applies to that.

File: src/link/section.cpp (hunk 1 above)
Comment (Rangi42) [reply src/link/section.cpp]: Sorry, I don't understand what you mean here. This is the logic structure we currently have:

```c++
} else if (A && B) {
	[fatal error];
} else if (!A || C) {
	[update target];
}
```

- `A` is `target.isAlignFixed`
- `B` is `(other.alignMask & target.alignOfs) != (target.alignMask & ofs)`
- `C` is `other.alignMask > target.alignMask`

I'm not seeing how a single `} else if (A) { ... }` block would work (nor how pattern matching would help if that were a thing). Can you write it out?

(Please note that I'd strongly prefer to avoid nesting 5 or more tab levels deep. `git grep -nP '^\t{5,}' include src` shows where we still do that -- src/link/sdas_obj.cpp has the majority of deep code (and is too niche for me to try refactoring); src/gfx/process.cpp and src/gfx/reverse.cpp also have pretty many (in part due to error reporting); and the remaining few dozen are all places I've carefully looked at before and decided it's not possible or not worth the cost to reduce nesting. We used to have a lot more deep code, and un-nesting it tended to uncover bugs.)

**Comment by Rangi42** [comment]
> I'm personally not convinced by the use of a LLM here, since the hard work (of narrowing the bug down) had already been performed, and a human would've been able to perform the fix in the same five minutes.

If you mean that you're not convinced it's a correct or complete bug fix, that's what PR review is for anyway -- if/when I'd come across this one-line discrepancy in manual code debugging, I can tell that I'd believe it to be correct, and would have opened this same PR no matter what. So regardless of LLMs, I'm looking for a second pair of eyes to verify that.

> Some friends asked me about this, and I've given a more lengthy analysis of my stance [...]

I'm... not going to get into that. 😅 I don't think GitHub Issues is the place for it, and the only reason I mentioned Codex at all was to give vulcandth proper credit, and to avoid claiming/implying that either of us personally read and understood the alignment-related code well enough to have found this. (I know I'd have taken more than five minutes investigating other possibilities before landing on this correct one.) Maybe in future I should just not mention if/how AI was involved, if it just causes unnecessary controversy over a one-line bugfix (and subsequent refactor that's entirely my judgement).

Edit:

> Yep, fix looks good, and the refactoring doesn't strike me as incorrect, so all good.

Oh okay, so you are convinced it's a good fix. Then I don't think anything else is relevant, at least not to be discussed in this issue. (I suppose if you want it to be in "a more public place", a GitHub Discussion would also work, if you want to move your stance description to there? Or your blog, if you feel like it's more personal-belief-related than RGBDS-maintenance-related.)

File: src/link/section.cpp (hunk 1 above)
Comment (Rangi42) [reply src/link/section.cpp]: ...is this what you have in mind?
```c++
} else if (A) {
    if (B) {
        foo();
    } else if (C) {
        bar();
    }
} else {
    bar();
}
```
This seems very obviously inferior -- instead of repeating "`A`" twice (literally just "`target.isAlignFixed`"), it repeats "`bar()`" twice (a stand-in for multiple statement lines), and as I feared it requires a deeper indent level. But if you had a better alternative in mind that doesn't repeat "`foo()`" or "`bar()`", I'm still missing it.

Comment (ISSOtm) [reply src/link/section.cpp]: Ah, right, it's an OR and not a AND. Never mind then.
