### PR TITLE
Fix RGBGFX reversal

### LINKED ISSUE #1420: RGBGFX does not validate tile indices
```console
% rgbgfx -r 40 -t bg_currents.bin -b 1 -o tileset.2bpp map.png
/usr/include/c++/14.1.1/bits/stl_vector.h:1149: constexpr std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](size_type) const [with _Tp = unsigned char; _Alloc = default_init_allocator<unsigned char, std::allocator<unsigned char> >; const_reference = const unsigned char&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
zsh: IOT instruction (core dumped)  rgbgfx -r 40 -t bg_currents.bin -b 1 -o tileset.2bpp /map.png
```

[assets.zip](https://github.com/user-attachments/files/16383363/assets.zip)

The tilemap references tile IDs that aren't present in the tile data (turns out they're loaded separately), but this shouldn't cause a crash.

### PR DESCRIPTION
**Pull request by Rangi42**
Fixes #1420 (but probably has more left to do)

```console
$ ./rgbgfx -r 40 -t assets/bg_currents.bin -b 1 -o assets/tileset.2bpp assets/map.png
FATAL: Tilemap references tile #192 at (6, 42), but the limit is 188
Conversion aborted after 1 error
```

### CODE REVIEW

File: src/gfx/reverse.cpp [hunk 1]
```diff
@@ -241,24 +242,27 @@ void reverse() {
...
 				}
 			}
 		} else {
-			for (auto id : *tilemap) {
-				if (id >= options.maxNbTiles[0]) {
-					warning(
-					    "Tile #%" PRIu8 " was referenced, but the limit is %" PRIu16,
-					    id,
-					    options.maxNbTiles[0]
+			size_t limit = std::min<size_t>(nbTiles, options.maxNbTiles[0]) + options.baseTileIDs[0];
```
Comment (ISSOtm) [inline src/gfx/reverse.cpp:256]: Not quite! It's possible for the “allowed” range to wrap around (e.g. `-N 128 -b 192`), so we want to compare `static_cast<uint8_t>(tileID - options.baseTileIDs[bank])`[^int] against `limit(bank)`[^lim].

Though, then the error message can become confusing; I'd suggest turning it into `...at ({tx}, {ty}), outside of the allowed [{options.baseTileIDs[bank]}, {static_cast<uint8_t>(options.baseTileIDs[bank] + limit(bank))}]`.

[^int]: Yes, that cast is necessary. Fuck integer promotion.
[^lim]: I don't remember the behaviour if tiles are referenced from bank 1, but `-N` is not passed to give its size?

File: src/gfx/reverse.cpp [hunk 2]
```diff
@@ -366,9 +370,8 @@ void reverse() {
 			    0x00,
 			    0x00,
 			};
-			uint8_t const *tileData = tileID > nbTileInstances - options.trim
-			                              ? trimmedTile.data()
-			                              : &tiles[tileID * tileSize];
+			uint8_t const *tileData =
+			    tileID > nbTiles ? trimmedTile.data() : &tiles[tileID * tileSize];
```
Comment (ISSOtm) [inline src/gfx/reverse.cpp:374]: Umm, shouldn't this be

```suggestion
			    tileID >= nbTiles ? trimmedTile.data() : &tiles[tileID * tileSize];
```

actually? If yes, then looks like we've never tested this, lol.

File: src/gfx/reverse.cpp [hunk 3]
```diff
@@ -117,8 +117,9 @@ void reverse() {
 	}
 
 	// By default, assume tiles are not deduplicated, and add the (allegedly) trimmed tiles
-	size_t nbTileInstances = tiles.size() / tileSize + options.trim; // Image size in tiles
-	options.verbosePrint(Options::VERB_INTERM, "Read %zu tiles.\n", nbTileInstances);
+	size_t nbTiles = tiles.size() / tileSize;
```
Comment (ISSOtm) [inline src/gfx/reverse.cpp:120]:
```suggestion
	size_t const nbTiles = tiles.size() / tileSize;
```

File: src/gfx/reverse.cpp [hunk 4]
```diff
@@ -117,8 +117,9 @@ void reverse() {
...
+	size_t nbTileInstances = nbTiles + options.trim; // Image size in tiles
+	options.verbosePrint(Options::VERB_INTERM, "Read %zu tiles.\n", nbTiles);
```
Comment (ISSOtm) [inline src/gfx/reverse.cpp:122]:
```suggestion
	options.verbosePrint(Options::VERB_INTERM, "Read %zu tiles.\n", nbTiles);
	size_t nbTileInstances = nbTiles + options.trim; // Image size in tiles
```

File: src/gfx/reverse.cpp [hunk 5]
```diff
@@ -241,24 +242,27 @@ void reverse() {
...
 		if (attrmap) {
-			for (auto [id, attr] : zip(*tilemap, *attrmap)) {
-				bool bank = attr & 1 << 3;
-				if (id >= options.maxNbTiles[bank]) {
+			for (auto [tileID, attribute] : zip(*tilemap, *attrmap)) {
+				if (bool bank = attribute & 1 << 3; tileID >= options.maxNbTiles[bank]) {
 					warning(
-					    "Tile #%" PRIu8 " was referenced, but the limit for bank %u is %" PRIu16,
-					    id,
+					    "Tilemap references tile #%" PRIu8 ", but the limit for bank %u is %" PRIu16,
```
Comment (ISSOtm) [inline src/gfx/reverse.cpp:248]: It would be nice if that error message could also mention the tile's coordinates.

(And, for that matter, I think the attrmap and palmap messages could also make use of that!)

File: src/gfx/reverse.cpp [hunk 6]
```diff
@@ -241,24 +242,27 @@ void reverse() {
 
 	if (tilemap) {
 		if (attrmap) {
-			for (auto [id, attr] : zip(*tilemap, *attrmap)) {
-				bool bank = attr & 1 << 3;
-				if (id >= options.maxNbTiles[bank]) {
+			for (auto [tileID, attribute] : zip(*tilemap, *attrmap)) {
+				if (bool bank = attribute & 1 << 3; tileID >= options.maxNbTiles[bank]) {
```
Comment (ISSOtm) [inline src/gfx/reverse.cpp:246]: This doesn't take `options.baseTileIDs` into account.

**Review by ISSOtm — COMMENTED** [review]
Here are some of the bugs I've spotted from my previous reading of this code...

I think you will understand why I found the task quite daunting. :[

File: src/gfx/reverse.cpp (hunk 1 above)
Comment (Rangi42) [reply src/gfx/reverse.cpp]: I'm not sure how or if to account for `baseTileIDs` here (see the other issue comment).

File: src/gfx/reverse.cpp (hunk 6 above)
Comment (ISSOtm) [reply src/gfx/reverse.cpp]: Yes, and that's the bug: you can't compare a tile ID to a number of tiles.

To make this clearer throughout the code, I'd suggest enforcing a naming convention “tile ID” for tilemap entries, as opposed to “tile offset” for indices into the tile data array.

File: src/gfx/reverse.cpp [hunk 7]
```diff
@@ -241,24 +253,34 @@ void reverse() {
...
-					warning(
-					    "Tile #%" PRIu8 " was referenced, but the limit is %" PRIu16,
-					    id,
-					    options.maxNbTiles[0]
+			size_t limit =
+			    std::min<size_t>(nbTiles, options.maxNbTiles[0]) + options.baseTileIDs[0];
+			for (size_t index = 0; index < nbTileInstances; ++index) {
+				if (uint8_t tileID = (*tilemap)[index]; tileID >= limit) {
+					size_t tx = index % width, ty = index / width;
+					fatal(
```
Comment (ISSOtm) [inline src/gfx/reverse.cpp:278]: Rather than terminating at the first violation, I'd like this to be an `error`, and after the loop, `if (nbErrors != 0) { giveUp(); }`

**Comment by Rangi42** [comment]
@ISSOtm Would you mind just pushing directly to this to get it resolved?

**Comment by ISSOtm** [comment]
Just rebased. cc @Rangi42!

File: src/gfx/reverse.cpp [hunk 8]
```diff
@@ -381,15 +443,14 @@ void reverse() {
...
-			if (tilemap.has_value()) {
-				tileID =
-				    (*tilemap)[index] - options.baseTileIDs[bank] + bank * options.maxNbTiles[0];
-			}
-			assume(tileID < nbTileInstances); // Should have been checked earlier
+			size_t tileOfs =
+			    tilemap ? static_cast<uint8_t>((*tilemap)[index] - options.baseTileIDs[bank])
+			                  + (bank ? nbTilesInBank[0] : 0)
+			            : index;
+			assume(tileOfs < nbTiles + options.trim); // Should have been checked earlier
```
[the remark this answers is not in the document]
Comment (ISSOtm) [reply src/gfx/reverse.cpp:453]: Then maybe
```suggestion
			// Should have been enforced above, this assertion is here for what slips through the cracks.
			assume(tileOfs < nbTiles + options.trim);
```

File: src/gfx/reverse.cpp [hunk 9]
```diff
@@ -254,71 +254,133 @@ void reverse() {
...
+		}
+
+		options.verbosePrint(
+		    Options::VERB_INTERM,
+		    "Nb tiles in bank {0: %" PRIu16 ", 1: %" PRIu16 "}\n",
+		    nbTilesInBank[0],
+		    nbTilesInBank[1]
+		);
+
+		for (int bank = 0; bank < 2; ++bank) {
```
[the remark this answers is not in the document]
Comment (ISSOtm) [reply src/gfx/reverse.cpp]: ...ah, `NB_TILE_BANKS` is not defined, so we get build failures. I'll revert this back to `2`, it's quite obvious what the `2` is about, since the index variable is quite explicitly called `bank`.

File: src/gfx/reverse.cpp (hunk 8 above)
[the remark this answers is not in the document]
Comment (Rangi42) [reply src/gfx/reverse.cpp:453]: Or just "This should have been enforced above."  No need to explain that assertions are there to double-check preconditions just in case. (If we actually expected anything to "slip through the cracks", we should be fixing the code to not do that.)

**Review by ISSOtm — APPROVED** [review]

**Comment by ISSOtm** [comment]
@Rangi42 is dealing with adding tests, including more structural changes; that'll be done in another PR.
