### PR TITLE
Fix linking tiny overlay files

### LINKED ISSUE #754: Linking as "tiny" can output too much with an overlay file
Test case:

```
SECTION "rom", ROM0[0]
ROM0Label::
DS $8000
```

`rgblink -t -O overlay.bin`, given some 32 KB overlay.bin file, should output a 32 KB ROM. It actually outputs 48 KB.

### PR DESCRIPTION
**Pull request by Rangi42**
Fixes #754

### CODE REVIEW

File: test/link/test.sh [hunk 1]
```diff
@@ -110,27 +121,45 @@ for i in fragment-align/*; do
...
+tryCmp $gbtemp $gbtemp2
+rc=$(($? || $rc))
+
+i="overlay.asm"
+startTest
+$RGBASM -o $otemp overlay/a.asm
+rgblink -o $gbtemp -t -O overlay/overlay.gb $otemp > $outtemp 2>&1
+tryDiff overlay/out.err $outtemp
+rc=$(($? || $rc))
+tryCmp overlay/out.gb $gbtemp
```
Comment (ISSOtm) [inline test/link/test.sh:139]: I would just add a comment pointing out that this test also intentionally checks the output's size.

**Review by ISSOtm — CHANGES_REQUESTED** [review]

**Review by ISSOtm — APPROVED** [review]
