### PR TITLE
Move definition of `_POSIX_C_SOURCE` to include/platform.hpp

### LINKED ISSUE #1111: Build fails on OpenBSD 7.2
This seems potentially related to: https://github.com/gbdev/rgbds/issues/1091

This will fix the problem, but I think there may be a better way, and someone more familiar with the codebase may have a better solution:
```
diff --git a/Makefile b/Makefile
index d39906ba..18f01279 100644
--- a/Makefile
+++ b/Makefile
@@ -42,7 +42,7 @@ CXXFLAGS      ?= -O3 -flto -DNDEBUG
 REALCFLAGS     := ${CFLAGS} ${WARNFLAGS} -std=gnu11 -I include \
                   -D_POSIX_C_SOURCE=200809L -D_ISOC11_SOURCE
 REALCXXFLAGS   := ${CXXFLAGS} ${WARNFLAGS} -std=c++17 -I include \
-                  -D_POSIX_C_SOURCE=200809L -fno-exceptions -fno-rtti
+                  -fno-exceptions -fno-rtti
 # Overridable LDFLAGS
 LDFLAGS                ?=
 # Non-overridable LDFLAGS
```

Full build output:
```
DEFS=-Dlr.type=ielr -Dparse.lac=full -Dparse.error=verbose -Dparse.error=detailed -Dapi.token.raw=true
src/link/object.c:672:14: warning: result of comparison of constant 1152921504606846975 with expression of type 'unsigned int' is always false [-Wtautological-constant-out-of-range-compare]
        if (nbFiles > SIZE_MAX / sizeof(*nodes))
            ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
In file included from src/gfx/main.cpp:16:
In file included from /usr/include/c++/v1/fstream:188:
In file included from /usr/include/c++/v1/istream:163:
In file included from /usr/include/c++/v1/ostream:140:
In file included from /usr/include/c++/v1/locale:218:
/usr/include/c++/v1/__bsd_locale_fallbacks.h:122:17: error: use of undeclared identifier 'vasprintf'; did you mean 'vsprintf'?
    int __res = vasprintf(__s, __format, __va);
                ^
/usr/include/c++/v1/cstdio:124:9: note: 'vsprintf' declared here
using ::vsprintf _LIBCPP_USING_IF_EXISTS;
        ^
In file included from src/gfx/main.cpp:16:
In file included from /usr/include/c++/v1/fstream:188:
In file included from /usr/include/c++/v1/istream:163:
In file included from /usr/include/c++/v1/ostream:140:
In file included from /usr/include/c++/v1/locale:218:
/usr/include/c++/v1/__bsd_locale_fallbacks.h:122:27: error: cannot initialize a parameter of type 'char *' with an lvalue of type 'char **'
    int __res = vasprintf(__s, __format, __va);
                          ^~~
/usr/include/stdio.h:269:21: note: passing argument to parameter here
int      vsprintf(char *, const char *, __va_list);
                        ^
src/gfx/main.cpp:351:31: warning: result of comparison of constant 256 with expression of type 'std::array<unsigned char, 2>::value_type' (aka 'unsigned char') is always false [-Wtautological-constant-out-of-range-compare]
                        if (options.baseTileIDs[0] >= 256) {
                            ~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~
src/gfx/main.cpp:367:31: warning: result of comparison of constant 256 with expression of type 'std::array<unsigned char, 2>::value_type' (aka 'unsigned char') is always false [-Wtautological-constant-out-of-range-compare]
                        if (options.baseTileIDs[1] >= 256) {
                            ~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~
src/gfx/main.cpp:482:27: warning: result of comparison of constant 256 with expression of type 'uint8_t' (aka 'unsigned char') is always false [-Wtautological-constant-out-of-range-compare]
                        if (options.nbPalettes > 256) {
                            ~~~~~~~~~~~~~~~~~~ ^ ~~~
3 warnings and 2 errors generated.
*** Error 1 in /home/rupert/src/rgbds (Makefile:169 'src/gfx/main.o': @c++ -O2 -pipe  -Wall -pedantic -std=c++17 -I include  -D_POSIX_C_SOURCE...)
```

### PR DESCRIPTION
**Pull request by Rangi42**
Fixes #1111

This is how https://github.com/google/flatbuffers/pull/6205 and https://github.com/WebAssembly/wabt/pull/1360 dealt with the problem. (Defining `_POSIX_C_SOURCE` is required on some platforms, like Cygwin, and breaks others, like BSD. CMake makes platform detection easy, but POSIX Make does not, which leaves in-source definition.)

This works in OpenBSD 7.5, and in Cygwin on Windows! And as our CI proves, it works in MinGW! :)

image

image

### CODE REVIEW

**Review by ISSOtm — APPROVED** [review]
Every day, we stray further away from ~~God~~ standards and sanity...

But that increases our platform coverage, so that's good in the end, lol.

(*And not to worry&mdash;we may be straying further away from those, but [we are inching closer and closer](https://github.com/ISSOtm/rsgbds/commits/asm) to our one and true saviour: :crab:*)

File: include/platform.hpp [hunk 1]
```diff
@@ -56,4 +56,9 @@
 	#define setmode(fd, mode) (0)
 #endif
 
+// MingGW and Cygwin need POSIX functions which are not standard C explicitly enabled
+#if defined(__MINGW32__) || defined(__MINGW32__) || defined(__CYGWIN__)
```
Comment (orbea) [inline include/platform.hpp:60]: @Rangi42 Why are you checking `__MINGW32__` twice?

Comment (Rangi42) [reply include/platform.hpp:60]: In case the first one fails. :3

Comment (Rangi42) [reply include/platform.hpp:60]: Fixed in c7a029a0515b87725926925b6d45af1a619d5f5d.
