### PR TITLE
Multiple bugfixes for linking with SDCC object files

### LINKED ISSUE #1466: Add support for indeterminate section type when linking with SDCC object files
Most sections created by SDCC are indeterminate, which causes linking to fail at https://github.com/gbdev/rgbds/blob/master/src/link/section.cpp#L231 .
See https://github.com/gbdev/rgbds/blob/master/src/link/sdas_obj.cpp#L333 .

### PR DESCRIPTION
**Pull request by RubenZwietering**
First commit fixes a bug which caused the fatal error: Unkown endianness type ''.
Second commit fixes a bug were clearing the line buffer of the object file was forgotten when filling up the next one.

Fixes #1466

### CODE REVIEW

**Review by ISSOtm — APPROVED** [review]
Thank you! Good catches ^^

**Comment by ISSOtm** [comment]
Compiling that test project raised a *third* bug, so might as well throw it in.

**Comment by ISSOtm** [comment]
I believe this would require a significant rearchitecting of RGBLINK, which would be outside the scope of this PR.

But if there is a simple (non-band-aid) fix, then sure, let's.

File: src/link/sdas_obj.cpp [hunk 1]
```diff
@@ -136,7 +136,8 @@ enum RelocFlags {
 };
 
 void sdobj_ReadFile(FileStackNode const &where, FILE *file, std::vector<Symbol> &fileSymbols) {
-	std::vector<char> line(256);
+	std::vector<char> line;
```
Comment (Rangi42) [inline src/link/sdas_obj.cpp:140]: Note to self, some other variables also have this problem:

```
src/gfx/process.cpp:    std::vector<Palette> palettes(nbPalettes);
src/gfx/process.cpp:    std::vector<Palette> palettes(options.palSpec.size());
src/link/object.cpp:    std::vector<std::unique_ptr<Section>> fileSections(nbSections);
test/gfx/randtilegen.cpp:       std::vector<uint8_t> data(height * 8 * width * 8 * SIZEOF_PIXEL);
test/gfx/randtilegen.cpp:       std::vector<uint8_t *> rowPtrs(height * 8);
```

File: src/link/sdas_obj.cpp [hunk 2]
```diff
@@ -223,6 +223,7 @@ void sdobj_ReadFile(FileStackNode const &where, FILE *file, std::vector<Symbol>
 
 	getToken(nullptr, "'H' line is too short");
 	uint32_t expectedNbSymbols = parseNumber(where, lineNo, token, numberType);
+	fileSymbols.reserve(expectedNbSymbols);
```
Comment (Rangi42) [inline src/link/sdas_obj.cpp:226]: I know that this technically guarantees `fileSymbols` won't reallocate with `expectedNbSymbols` or fewer items, but it's not nonlocally obvious. In some parts of the code we use `std::deque` for collections that shouldn't move their items; in others, we have collections of indexes or pointers; and a third alternative would be to error if we exceed the expected number of symbols.

My preference would be for a `std::deque` here; it's a simpler change than the others. (And as we discussed, it seems *possible* that some weird SDCC object could have more symbols than expected but still ought to work.)

File: src/link/object.cpp [hunk 3]
```diff
@@ -354,7 +354,11 @@ static void readSection(
 	tryGetc(
 	    uint8_t, byte, file, "%s: Cannot read \"%s\"'s type: %s", fileName, section.name.c_str()
 	);
-	section.type = (SectionType)(byte & 0x3F);
+	if ((byte & 0x3F) >= SECTTYPE_INVALID) {
+		errx("\"%s\" has unknown section type 0x%02x", section.name.c_str(), byte & 0x3F);
+	} else {
+		section.type = SectionType(byte & 0x3F);
+	}
```
Comment (Rangi42) [inline src/link/object.cpp:361]:
```suggestion
	if (uint8_t type = byte & 0x3F; type >= SECTTYPE_INVALID) {
		errx("\"%s\" has unknown section type 0x%02x", section.name.c_str(), type);
	} else {
		section.type = SectionType(type);
	}
```

File: src/link/sdas_obj.cpp [hunk 4]
```diff
@@ -826,7 +826,37 @@ void sdobj_ReadFile(FileStackNode const &where, FILE *file, std::vector<Symbol>
...
+			// Otherwise, how would the type already be known at this point?
+			assume(section->isAddressFixed);
+
+			if (!sect_HasData(section->type)) {
+				if (!section->data.empty()) {
+					fatal(
+					    &where,
+					    lineNo,
+					    "\"%s\" is implicitly defined as a %s section (being at address $%04" PRIx16
+					    "), but it has data! (Was a bad `__at()` value used?)",
```
Comment (Rangi42) [inline src/link/sdas_obj.cpp:840]: Is "`__at()`" something that GBDK/SDCC users would know the meaning of? Something they write themselves?

File: src/link/script.y
Comment (Rangi42) [inline src/link/script.y:1]: I don't want to squash this PR because its commits implement multiple bugfixes and new features; however, in that case, this code change should be separate from the doc change (and the doc change could be merged with the "floating bank" code change previously).

**Review by Rangi42 — CHANGES_REQUESTED** [review]

File: src/link/sdas_obj.cpp (hunk 4 above)
Comment (ISSOtm) [reply src/link/sdas_obj.cpp:840]: Yeah, it's a special C attribute: `static char __at(0xC0DE) var;`.

File: src/link/sdas_obj.cpp (hunk 1 above)
Comment (ISSOtm) [reply src/link/sdas_obj.cpp:140]: Is it a problem? Several of those variables *do* get filled up to capacity afterwards.

File: src/link/sdas_obj.cpp (hunk 2 above)
Comment (ISSOtm) [reply src/link/sdas_obj.cpp:226]: It is anything but a simple change, since the symbols get passed around all the time, and this needs to be homogeneous with RGBDS objects too. So this would change a *lot* of function signatures, and that's starting to overflow the scope of the PR.

I'll make the warning into an error.

File: src/link/sdas_obj.cpp (hunk 1 above)
Comment (Rangi42) [reply src/link/sdas_obj.cpp:140]: I'm at least noting them here for me to double-check later.

File: man/rgblink.5 [hunk 5]
```diff
@@ -86,6 +86,19 @@ If the bank has never been active thus far, the
 .Dq current address
 defaults to the beginning of the bank
 .Pq e.g. Ad $4000 No for Ic ROMX No sections .
+.Pp
+Instead of giving a bank number, the keyword
+.Ic FLOATING
+can be used instead; this binds the subsequent sections to no bank in particular (except if the type only contains a single bank, in which case
+.Ic FLOATING
+has no effect).
```
Comment (Rangi42) [inline man/rgblink.5:94]:
```suggestion
Instead of giving a bank number, the keyword
.Ic FLOATING
can be used instead; this sets the type of the subsequent sections without binding them to a particular bank.
(If the type only allows a single bank, e.g.
.Ic ROM0 ,
then
.Ic FLOATING
is valid but redundant and has no effect.)
```

File: src/link/script.y [hunk 6]
```diff
@@ -388,6 +392,20 @@ static void setActiveTypeAndIdx(SectionType type, uint32_t idx) {
 	}
 }
 
+static void setFloatingSectionType(SectionType type) {
+	if (nbbanks(type) == 1) {
+		setActiveTypeAndIdx(type, 0); // There is only a single bank anyway, so just set the index to 0.
```
Comment (Rangi42) [inline src/link/script.y:397]: Should this give a warning, since `ROM0 FLOATING` or `WRAM0 FLOATING` are redundant and may indicate a mistake?

File: src/link/sdas_obj.cpp (hunk 1 above)
Comment (Rangi42) [reply src/link/sdas_obj.cpp:140]: Okay, yeah, they all look fine.

**Review by Rangi42 — CHANGES_REQUESTED** [review]

File: src/link/script.y (hunk 6 above)
Comment (ISSOtm) [reply src/link/script.y:397]: OTOH it could make sense if the script is auto-generated, which seems plausible for toolchains. And RGBLINK doesn't have a warning flag system, so... eh?

**Review by Rangi42 — APPROVED** [review]

**Review by ISSOtm — APPROVED** [review]
Alright! All of those bugfixes are good, so I think it's worth upstreaming all of them rather than sitting on them.

If more are found while @RubenZwietering experiments with the SDCC integration, then we'll merge those in a separate PR. Sounds good?
