### PR TITLE
Fix expansions that start from the end of another expansion

### LINKED ISSUE #696: Expanding `recurse EQUS "recurse"` or `recurse EQUS "\{recurse\}"` hangs rgbasm
This was noted in #557:

> tokens that end precisely at the end of an `EQUS` are not reported as coming from within the `EQUS`. It means that `recurse EQUS "recurse"` does infinitely hang RGBASM.

### PR DESCRIPTION
**Pull request by Rangi42**
Do not free an expansion until its offset is *past* its size. This means potentially freeing a nested stack of expansions all at once.

Fixes #696

### CODE REVIEW

File: src/asm/lexer.c [hunk 1]
```diff
@@ -736,7 +736,9 @@ static char const *readMacroArg(char name)
 static int peekInternal(uint8_t distance)
 {
 	for (struct Expansion *exp = lexerState->expansions; exp; exp = exp->parent) {
-		assert(exp->offset < exp->size);
+		assert(exp->offset <= exp->size);
+		if (exp->offset == exp->size)
```
Comment (ISSOtm) [inline src/asm/lexer.c:740]: Maybe add a comment explaiing in which case this gets triggered?
Additionally, this check is unnecessary, as if it's true, the rest of the loop is a no-op anyway.

File: src/asm/lexer.c [hunk 2]
```diff
@@ -870,16 +872,18 @@ static void shiftChar(void)
...
 
+restart:
 	if (lexerState->expansions) {
 		/* Advance within the current expansion */
-		assert(lexerState->expansions->offset < lexerState->expansions->size);
+		assert(lexerState->expansions->offset <= lexerState->expansions->size);
 		lexerState->expansions->offset++;
-		if (lexerState->expansions->offset == lexerState->expansions->size) {
+		if (lexerState->expansions->offset > lexerState->expansions->size) {
 			/* When an expansion is done, free it and move up to its parent */
```
Comment (ISSOtm) [inline src/asm/lexer.c:881]:
```suggestion
			/* When moving one past an expansion's end, free it and move up to its parent */
```

**Review by ISSOtm — CHANGES_REQUESTED** [review]

File: src/asm/lexer.c (hunk 2 above)
Comment (ISSOtm) [reply src/asm/lexer.c:881]: Actually, this should say "try the movement again with its parent", or something to that effect. That would explain the `goto restart;`.

File: src/asm/lexer.c (hunk 1 above)
Comment (Rangi42) [reply src/asm/lexer.c:740]: If you have `foo EQUS "bar + 2"`, `bar EQUS "qux"`, and `qux EQUS "hello"`, then to tokenize "`hello`" as an identifier the lexer has to `peek` past it. To do that, `peekInternal` has to `continue` down from the expansion of `qux`, then from the expansion of `bar`, into the expansion of `foo`, and get the space character from there.

I'll add a comment to that effect.

Comment (ISSOtm) [reply src/asm/lexer.c:740]: If this check is true, then `exp->size - exp->offset` is zero, thus the check below is guaranteed to be false (since `distance` is unsigned, therefore positive), and then `distance` will be decreased by 0.
Hence, the rest of the loop is implicitly skipped anyway.

Comment (ISSOtm) [reply src/asm/lexer.c]: (Since it's an exceptional case, I still think it's worth adding a comment, just not special-case it. I'm curious as to the compiler's behavior regarding this, though :P)

Comment (Rangi42) [reply src/asm/lexer.c]: Added a comment.

**Review by ISSOtm — APPROVED** [review]

**Comment by ISSOtm** [comment]
'tis a surprisingly simple fix to an issue that seemed very complex to handle :man_shrugging:

**Comment by Rangi42** [comment]
I think it's only possible because now there's maximum 1 lookahead, and it only needs to be aware of one expansion nesting at a time. Previously `ld [FF_OO PLUS_C]`, with nested expansions and extra whitespace in those two `equ`s, would have been problematic.
